### ISSUE TITLE
Error when running Set Background

### ISSUE THREAD

**Issue by Jhsmit** [SingleMolecule/iSBatch#19]
/////
convert fileNode
does not apply to this level.
Exception in thread "Thread-32" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.RangeCheck(ArrayList.java:547)
	at java.util.ArrayList.get(ArrayList.java:322)
	at imageOperations.NodeToImageStack.<init>(NodeToImageStack.java:35)
	at operations.flatImages.SetBackGround.run(SetBackGround.java:202)
	at operations.flatImages.SetBackGround.visit(SetBackGround.java:250)
	at model.Sample.accept(Sample.java:44)
	at operations.OperationRunner.run(OperationRunner.java:52)
	at java.lang.Thread.run(Thread.java:662)

**Comment by vcaldas** [comment]
@Jhsmit I could not reproduce the error. Could you send more details? Looks like some parameters are wrong when you import the files into the database.
If possible, check your import parameters with a smaller dataset and let me know.
